### ISSUE TITLE
[question] - no refiner workflow

### ISSUE THREAD

**Issue by tastez** [hustille/ComfyUI_Fooocus_KSampler#3]
in case we don't want to use a refiner - do we just plug the same model for the refiner, and set "refiner switch steps" to 1 and up the samples for the "steps"

**Comment by hustille** [comment]
You can use the same model. In that case _refiner_switch_step_ is more or less irrelevant. Don't change _steps_, that is the combined value. The sampler runs from step 0 to _refiner_switch_step_ on _model_ and from _refiner_switch_step_ to _steps_ on _refiner_model_. If you set _refiner_switch_step_ to 0 or > _steps_ it will not switch.

**Comment by hustille** [comment]
Why not just a standard sampler? Do you have any insight into the changes Fooocus makes? In the tests I have run the differences were minimal.

**Comment by tastez** [comment]
hmm good point. I had no idea actually and assumed it is different in some way.
I am no chanbging start_at_step / end_at_step but I am plugging in the same model and changing steps to 8+ and refiner to 1 and it feels like sdxl without a refiner.
thanks for reply!

**Comment by hustille** [comment]
It _is_ different. I just have no idea under what circumstances those differences become relevant or at least visible. It's possible that I have overlooked something and there are still differences in Fooocus which I haven't pulled over, but I don't think so.

The only major thing is the _sharpness_ parameter, which does some local modifications without changing the overall picture. Useful values seem to go up to 20 or so, just play around with it.

**Comment by tastez** [comment]
yeah great. thanks a ton for this node its great and compact!
